### ISSUE TITLE
some issues in running pytorch_ncrf.py

### ISSUE THREAD

**Issue by AiHubCN** [thespectrewithin/cross-lingual_NER#3]
Hi~

There are some issues when I run the pytorch_ncrf.py:

Traceback (most recent call last):
  File "pytorch_ncrf.py", line 427, in <module>
    main()
  File "pytorch_ncrf.py", line 270, in main
    word_dict, word_vector = create_word_index(word_vec_path, vocab_size, word_embed_size, True)
  File "/home/***/cross-lingual_NER/util.py", line 51, in create_word_index
    vec = np.array([float(i) for i in l[1:]], dtype = 'float32')
  File "/home/***/cross-lingual_NER/util.py", line 51, in <listcomp>
    vec = np.array([float(i) for i in l[1:]], dtype = 'float32')
ValueError: could not convert string to float: 'el'

I think the reason may be: there's a weird character in the word embedding file that Python 3.6 handles differently. So I modified the util.py according to the 71th~77th line in load_muse.py. But I also got error:

pytorch_ncrf.py:84: UserWarning: volatile was removed (Variable.volatile is always False)
  filler = Variable(torch.zeros((clen - zero_index, 2*self.chidden_size)), volatile=char_input.volatile, requires_grad=False).cuda()
Traceback (most recent call last):
  File "pytorch_ncrf.py", line 427, in <module>
    main()
  File "pytorch_ncrf.py", line 363, in main
    loss, predict = model(word_input, char_input, word_length_input, char_length_input, label_input)
  File "/home/***/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "pytorch_ncrf.py", line 128, in forward
    predict = self.crf.decode(word_output, words.ne(Constants.PAD).float(), 1)
  File "/home/***/cross-lingual_NER/pytorch_crf.py", line 188, in decode
    pi[0] = energy[:, 0, -1, leading_symbolic:-1]
RuntimeError: The expanded size of the tensor (1) must match the existing size (9) at non-singleton dimension 2

**Comment by thespectrewithin** [comment]
use pytorch 0.3.0
